<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllClient()
    {
        return $this->createQueryBuilder('c')
        ->orderBy('c.nom', 'ASC')
        ->getQuery()
        ->getResult();
    }
}
