<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * FirmwareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmwareRepository extends \Doctrine\ORM\EntityRepository
{
}
