<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * HistoVenteAutreProduitFiniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoVenteAutreProduitFiniRepository extends \Doctrine\ORM\EntityRepository
{
}
