<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * HistoVenteLecteurAutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoVenteLecteurAutreRepository extends \Doctrine\ORM\EntityRepository
{
}
