<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * HistoPretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoPretRepository extends \Doctrine\ORM\EntityRepository
{
    public function gethistoPretLecteur($numSerie)
    {
        return $this->createQueryBuilder('hp')
        ->join('hp.client', 'c')
        ->addSelect('hp', 'c')
        ->where('hp.numSerie= :numSerie')
        ->setParameter('numSerie', $numSerie)
        ->getQuery()
        ->getResult();
    }
}
