<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * HistoVenteBadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoVenteBadgeRepository extends \Doctrine\ORM\EntityRepository
{
}
