<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * HistoRepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoRepriseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReprise($numSerie)
    {
        return $this->createQueryBuilder('hr')
        ->join('hr.test', 't')
        ->join('t.etape', 'e')
        ->addSelect('hr', 't', 'e')
        ->where('hr.numSerie = :numSerie')
        ->setParameter('numSerie', $numSerie)
        ->getQuery()
        ->getResult();
    }
}
