<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * LecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFicheDescriptive($numSerie)
    {
        return $this->createQueryBuilder('l')
        ->join('l.versionFicheDescriptive', 'vfd')
        ->join('vfd.ficheDescriptiveOption', 'fdo')
        ->join('fdo.optionFicheDescriptive', 'ofd')
        ->join('fdo.ficheDescriptive', 'fd')
        ->addSelect('l', 'vfd', 'fdo', 'ofd', 'fd')
        ->where('l.numSerie = :numSerie')
        ->setParameter('numSerie', $numSerie)
        ->getQuery()
        ->getResult();        
    }
    
    public function getAllInfoSav($numSerie)
    {
        return $this->createQueryBuilder('l')
        ->join('l.versionFicheDescriptive', 'vfd')
        ->join('vfd.ficheDescriptiveOption', 'fdo')
        ->join('fdo.optionFicheDescriptive', 'ofd')
        ->join('fdo.ficheDescriptive', 'fd')
        ->addSelect('l', 'vfd', 'fdo', 'ofd', 'fd')
        ->groupBy('l.numSerie')
        ->where('l.numSerie IN(:numSerie)')
        ->setParameter('numSerie', array_values($numSerie))
        ->getQuery()
        ->getResult();        
    }
}
