<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * LecteurAutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecteurAutreRepository extends \Doctrine\ORM\EntityRepository
{
}
