<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * NomenclatureLecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureLecteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNomenclature($idLecteur)
    {
        return $this->createQueryBuilder('nl')
        ->join('nl.versionNomenclature', 'vn')
        ->join('vn.nomenclature', 'n')
        ->join('nl.firmware', 'f')
        ->addSelect('n', 'vn', 'nl', 'f')
        ->where('nl.idLecteur = :idLecteur')
        ->setParameter('idLecteur', $idLecteur)
        ->getQuery()
        ->getResult();    
    }
}
