<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * NomenclatureFicheDescriptiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureFicheDescriptiveRepository extends \Doctrine\ORM\EntityRepository
{
}
