<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * OptionFicheDescriptiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionFicheDescriptiveRepository extends \Doctrine\ORM\EntityRepository
{
}
