<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * PretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PretRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllPret()
    {
        return $this->createQueryBuilder('p')
        ->join('p.client', 'c')
        ->join('p.versionFicheDescriptive', 'vfd')
        ->join('vfd.ficheDescriptiveOption', 'fdo')
        ->join('fdo.optionFicheDescriptive', 'ofd')
        ->join('fdo.ficheDescriptive', 'fd')
        ->join('ofd.optionProduitFini', 'opf')
        ->addSelect('c', 'p', 'vfd', 'fdo', 'ofd', 'fd', 'opf')
        ->orderBy('p.dateEnvoi', 'DESC')
        ->getQuery()
        ->getResult();
    }
}
