<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * ProduitFiniAutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFiniAutreRepository extends \Doctrine\ORM\EntityRepository
{
}
