<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * SavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotReturn()
    {
        return $this->createQueryBuilder('s')
        ->where('s.dateRenvoi = 0000-00-00')
        ->getQuery()
        ->getResult();
    }
}
