<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * VersionFicheDescriptiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionFicheDescriptiveRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNomLecteurById($id)
    {
        $req = $this->createQueryBuilder('vfd')
        ->join('vfd.ficheDescriptiveOption', 'fdo')
        ->join('fdo.optionFicheDescriptive', 'ofd')
        ->join('fdo.ficheDescriptive', 'fd')
        ->addSelect('vfd', 'fdo', 'ofd', 'fd')
        ->where('vfd.id = :id')
        ->setParameter('id', $id)
        ->getQuery()
        ->getResult();  

        $version = $req[0]->getVersion();
        $nom = $req[0]->getFicheDescriptiveOption()->getFicheDescriptive()->getNom();

        $listeOption = '';
        foreach ($req[0]->getFicheDescriptiveOption()->getOptionFicheDescriptive() as $option) 
        {
            $listeOption .= '-'.$option->getOptionProduitFini()->getAbreviation();
        }

        return $nom.$listeOption.'-V'.$version;      
    }
}
