<?php

namespace IC\ProduitFiniBundle\Repository;

/**
 * VersionNomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionNomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
}
