<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * ApproLecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApproLecteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApproLecteur()
    {
        return $this->createQueryBuilder('al')
        ->join('al.appro', 'a')
        ->join('al')
        ->join('al.typeLecteurAutre', 'tla')
        ->addSelect('a', 'tla')
        ->orderBy('al.idCommande')
        ->where('a.typeProduit = 3')
        ->getQuery()
        ->getResult();
    }
}
