<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllBadge()
    {
        return $this->createQueryBuilder('b')
        ->join('b.typeBadge', 'tb')
        ->addSelect('tb')
        ->getQuery()
        ->getResult();
    }
}
