<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * BadgeFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
