<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * ComposantNomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantNomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComposantNomenclatureMP($id)
	{
		return $this->createQueryBuilder('nc')
		->join('nc.composant', 'c')
		->join('c.famille', 'f')
		->join('c.sousFamille', 'sf')
		->addSelect('nc', 'c')
        ->orderBy('c.nom')
		->where('nc.idVersion = :id')
		->setParameter('id', $id)
		->getQuery()
		->getResult();
	}
}
