<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * ComposantFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantFournisseurRepository extends \Doctrine\ORM\EntityRepository
{

}
