<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * ComposantSousTraitantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantSousTraitantRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComposantSt($id)
	{
		return $this->createQueryBuilder('cst')
        ->join('cst.sousTraitant', 'st')
        ->addSelect('cst', 'st')
		->where('cst.idSousTraitant = :id')
		->setParameter('id', $id)
		->getQuery()
		->getResult();
	}
    
    public function getComposantBySousTraitant($idComposant, $idSousTraitant)
    {
		return $this->createQueryBuilder('cst')
        ->join('cst.sousTraitant', 'st')
        ->addSelect('cst', 'st')
		->where('cst.idComposant = :idComposant')
        ->andWhere('cst.idSousTraitant = :idSousTraitant')
		->setParameter('idComposant', $idComposant)
        ->setParameter('idSousTraitant', $idSousTraitant)
		->getQuery()
		->getResult();        
    }
}
