<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComposantFournisseurById($listeIdComposant)
    {
        for($i = 0; $i < count($listeIdComposant); $i++)
        {
            $listeId[] = $listeIdComposant[$i]['idComposant'];
        }
        
        $req = $this->createQueryBuilder('f')
        ->join('f.composantFournisseur', 'cf')
        ->join('cf.composant', 'c')
        ->orderBy('c.nom')
        ->addSelect('c', 'cf')
        ->orderBy('cf.idFournisseur', 'ASC')
        ->where('cf.idComposant IN (:id)')
        ->setParameter('id', $listeId);
       
        return $req->getQuery()->getResult();           
    }
    
    public function getAllPF($idType)
    {
        $req = $this->createQueryBuilder('f');
        
        if($idType == 2)
        {
            $req->join('f.badgeFournisseur', 'bf')
            ->join('bf.typeBadge', 'tb')
            ->addSelect('f', 'bf', 'tb');
        }
        elseif($idType == 3)
        {
            $req->join('f.lecteurAutre', 'la')
            ->addSelect('f', 'la');            
        }
        elseif($idType == 4)
        {
            $req->join('f.autre', 'a')
            ->addSelect('f', 'a');            
        }
        
        return $req->getQuery()
        ->getResult();
    }
}
