<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * MoqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoqRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMoqAndFournisseur($listeIdComposant)
    {
        for($i = 0; $i < count($listeIdComposant); $i++)
        {
            $listeId[] = $listeIdComposant[$i]['idComposant'];
        }
        
        $req = $this->createQueryBuilder('m')
        ->join('m.fournisseur', 'f')
        ->join('m.composant', 'c')
        ->addSelect('c', 'f')
        ->orderBy('m.idFournisseur', 'ASC')
        ->where('m.idComposant IN (:id)') 
        ->setParameter('id', $listeId);
        
        /*
        if(!empty($critere['famille']))
        {
                $req->where('c.idFamille IN (:id)') 
                ->setParameter('id', $critere['famille']);
        }
        
        if(!empty($critere['sousFamille']))
        {
                $req->andWhere('c.idSousFamille IN (:id1)') 
                ->setParameter('id1', $critere['sousFamille']);
        }
        */
        return $req->getQuery()->getResult();   
    }
}
