<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * ProduitFiniNomenclature
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFiniNomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComposantNomenclaturePF($id)
	{
		return $this->createQueryBuilder('pfn')
		->join('pfn.composant', 'c')
		->join('c.famille', 'f')
		->leftJoin('c.sousFamille', 'sf')
		->addSelect('pfn', 'c')
        ->orderBy('c.nom')
		->where('pfn.idVersion = :id')
		->setParameter('id', $id)
		->getQuery()
		->getResult();
	}
}
