<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * SousTypeLecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTypeLecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
