<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * SousTraitantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTraitantRepository extends \Doctrine\ORM\EntityRepository
{
}
