<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * TypeLecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLecteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllTypeLecteur()
    {
        return $this->createQueryBuilder('tl')
        ->join('tl.fournisseur', 'f')
        ->addSelect('f')
        ->where('tl.idFournisseur != 0')
        ->getQuery()
        ->getResult();
    }
}
