<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * TypeBadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBadgeRepository extends \Doctrine\ORM\EntityRepository
{
}
