<?php

namespace IC\TestBundle\Repository;

/**
 * CarteHsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteHsRepository extends \Doctrine\ORM\EntityRepository
{
}
