<?php

namespace IC\TestBundle\Repository;

/**
 * EtapeNomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeNomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllEtapeByNomenclature($idVersionNomenclature)
    {
        return $this->createQueryBuilder('en')
        ->join('en.etape', 'e')
        ->addSelect('en', 'e')
        ->orderBy('en.ordre', 'ASC')
        ->where('en.idVersionNomenclature = :idVersionNomenclature')
        ->setParameter('idVersionNomenclature', $idVersionNomenclature)
        ->getQuery()
        ->getresult();
    }
    
    public function getListeTestByEtape($idVersionNomenclature, $ordre)
    {
        return $this->createQueryBuilder('en')
        ->leftJoin('en.testNomenclature', 'tn')
        ->leftJoin('tn.test', 't')
        ->addSelect('en', 'tn', 't')
        ->where('en.idVersionNomenclature = :idVersionNomenclature AND en.ordre = :ordre')
        ->setparameter('idVersionNomenclature', $idVersionNomenclature)
        ->setParameter('ordre', $ordre)
        ->getQuery()
        ->getResult();
    }
}
