<?php

namespace IC\TestBundle\Repository;

/**
 * HistoCarteHsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoCarteHsRepository extends \Doctrine\ORM\EntityRepository
{
}
