<?php

namespace IC\TestBundle\Repository;

/**
 * LotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListeLotAndNomenclature()
    {
        return $this->createQueryBuilder('l')
        ->join('l.versionNomenclature', 'vn')
        ->join('vn.nomenclature', 'n')
        ->getQuery()
        ->getResult();
    }
    
    public function getLotById($id)
    {
        return $this->createQuerybuilder('l')
        ->join('l.versionNomenclature', 'vn')
        ->join('vn.nomenclature', 'n')
        ->addSelect('l', 'vn', 'n')
        ->where('l.id = :idLot')
        ->setParameter('idLot', $id)
        ->getQuery()
        ->getResult();
    }
}
