<?php

namespace IC\TestBundle\Repository;

/**
 * NomenclatureLecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureLecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
