<?php

namespace IC\TestBundle\Repository;

/**
 * OptionProduitFiniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionProduitFiniRepository extends \Doctrine\ORM\EntityRepository
{
}
