<?php

namespace IC\TestBundle\Repository;

/**
 * ProduitFiniNomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFiniNomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNomenclaturePF($idVersion)
    {
        return $this->createQueryBuilder('pfn')
        ->join('pfn.composant', 'c')
        ->where('pfn.idVersion = :version')
        ->setParameter('version', $idVersion)
        ->getQuery()
        ->getResult();
    }
}
