<?php

namespace IC\TestBundle\Repository;

/**
 * RepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepriseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLotAndRepriseByNumSerie($numSerie)
    {
        return $this->createQueryBuilder('r')
        ->join('r.lot', 'l')
        ->where('r.numSerie = :numSerie')
        ->setParameter('numSerie', $numSerie)
        ->getQuery()
        ->getResult();
    }
}
