<?php

namespace IC\TestBundle\Repository;

/**
 * SavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavRepository extends \Doctrine\ORM\EntityRepository
{
}
