<?php

namespace IC\TestBundle\Repository;

/**
 * TestNomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestNomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
}
