<?php

namespace IC\TestBundle\Repository;

/**
 * VersionFicheDescriptiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionFicheDescriptiveRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFicheByVersion($listeId)
    {
        return $this->createQueryBuilder('vfd')
        ->join('vfd.nomenclatureFicheDescriptive', 'nfd')
        ->join('nfd.versionNomenclature', 'vn')
        ->join('vn.nomenclature', 'n')
        ->join('vfd.ficheDescriptiveOption', 'fdo')
        ->join('fdo.ficheDescriptive', 'fd')
        ->join('fdo.optionFicheDescriptive', 'ofd')
        ->join('ofd.optionProduitFini', 'opf')
        ->orderBy('nfd.idVersionNomenclature', 'ASC')
        ->addSelect('vfd', 'nfd', 'fdo', 'fd', 'ofd', 'opf', 'vn', 'n')
        ->where('vfd.id IN ('.$listeId.')')
        ->getQuery()
        ->getresult();
    }
}
