<?php

namespace IC\AdministrationBundle\Repository;

/**
 * BadgeFournisseurrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListBadgeById($idBadge)
    {
       $req = $this->createQueryBuilder('fb')
        ->join('fb.fournisseur', 'f')
        ->join('fb.typeBadge', 'tb')
        ->addSelect('tb', 'f')
        ->orderBy('fb.idFournisseur', 'ASC')
        ->where('fb.idTypeBadge =:id')
        ->setParameter('id', $idBadge);
        
        /*
        if(!empty($critere['famille']))
        {
                $req->where('c.idFamille IN (:id)') 
                ->setParameter('id', $critere['famille']);
        }
        
        if(!empty($critere['sousFamille']))
        {
                $req->andWhere('c.idSousFamille IN (:id1)') 
                ->setParameter('id1', $critere['sousFamille']);
        }
        */
        return $req->getQuery()->getResult();          
    }
}
