<?php

namespace IC\AdministrationBundle\Repository;

/**
 * ComposantFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListComposantById($idComposant)
    {
       $req = $this->createQueryBuilder('cf')
        ->join('cf.fournisseur', 'f')
        ->join('cf.composant', 'c')
        ->orderBy('c.nom')
        ->addSelect('c', 'f')
        ->orderBy('cf.idFournisseur', 'ASC')
        ->where('cf.idComposant =:id')
        ->setParameter('id', $idComposant);
        
        return $req->getQuery()->getResult();          
    }
      
}
