<?php

namespace IC\AdministrationBundle\Repository;

/**
 * ComposantNomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantNomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComposantByNomenclature($idNomenclature)
    {
        return $this->createQueryBuilder('cn')
        ->where('cn.idVersion = :idVersion')
        ->setParameter('idVersion', $idNomenclature)
        ->getQuery()
        ->getResult();
    }
}
