<?php

namespace IC\AdministrationBundle\Repository;

/**
 * FicheDescriptiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheDescriptiveRepository extends \Doctrine\ORM\EntityRepository
{

}
