<?php

namespace IC\AdministrationBundle\Repository;

/**
 * NomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureRepository extends \Doctrine\ORM\EntityRepository
{ 
    public function getLastNomenclature()
    {
        return $this->createQueryBuilder('n')
        ->orderBy('n.id', 'DESC')
        ->getQuery()
        ->getResult();        
    }
    
    public function getAllFirmware()
    {
        return $this->createQueryBuilder('n')
        ->leftJoin('n.firmware', 'f')
        ->getQuery()
        ->getResult();   
    }
}
