<?php

namespace IC\AdministrationBundle\Repository;

/**
 * NomenclatureFicheDescriptiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureFicheDescriptiveRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNomenlatures($idFiche)
    {
        return $this->createQuerybuilder('nfd')
        ->join('nfd.versionNomenclature', 'vn')
        ->addSelect('nfd', 'vn')
        ->where('nfd.idVersionFicheDescriptive = :idFiche')
        ->setParameter('idFiche', $idFiche)
        ->getQuery()
        ->getResult();
    }
}
