<?php

namespace IC\AdministrationBundle\Repository;

/**
 * SousTypeBadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTypeBadgeRepository extends \Doctrine\ORM\EntityRepository
{
}
