<?php

namespace IC\AdministrationBundle\Repository;

/**
 * TestNomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestNomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListTestByNomenclature($idEtape)
    {
        return $this->createQueryBuilder('ltn')
        ->join('ltn.etape', 'vn')
        ->where('ltn.idVersion = :idVersion')
        ->setParameter(':idVersion', $idEtape);
    }
}
