<?php

namespace IC\AdministrationBundle\Repository;

/**
 * TypeLecteurAutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLecteurAutreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllLecteurAutre()
    {
        return $this->createQueryBuilder('tla')
        ->join('tla.fournisseur', 'f')
        ->join('tla.sousTypeLecteur', 'stl')
        ->addSelect('f', 'stl')
        ->getQuery()->getResult();
    }
}
