<?php

namespace IC\AdministrationBundle\Repository;

/**
 * TypeLecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLecteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllTypeLecteur()
    {
        return $this->createQueryBuilder('tl')
        ->join('tl.nomenclature', 'n')
        ->join('tl.sousTypeLecteur', 'stl')
        ->addSelect('n', 'stl')
        ->getQuery()->getResult();
    }
    
    public function getTypeById($id)
    {
        return $this->createQueryBuilder('tl')
        ->join('tl.nomenclature', 'n')
        ->join('tl.sousTypeLecteur', 'stl')
        ->addSelect('n', 'stl')
        ->where('tl.id = :id')
        ->setParameter('id', $id)
        ->getQuery()->getResult();
    }
}
