<?php

namespace IC\AdministrationBundle\Repository;

/**
 * VersionFicheDescriptiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionFicheDescriptiveRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNbVersion($idFicheDescriptiveOption)
    {
        return $this->createQueryBuilder('vfd')
        ->select('COUNT(vfd)')
        ->where('vfd.idFicheDescriptiveOption = :idFicheDescriptiveOption')
        ->setParameter('idFicheDescriptiveOption', $idFicheDescriptiveOption)
        ->getQuery()
        ->getSingleScalarResult();
    }
}
