<?php

namespace IC\AffichageBundle\Repository;

/**
 * AutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutreRepository extends \Doctrine\ORM\EntityRepository
{
}
