<?php

namespace IC\AffichageBundle\Repository;

/**
 * FicheDescriptiveOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheDescriptiveOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
