<?php

namespace IC\AffichageBundle\Repository;

/**
 * ProduitFiniAutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFiniAutreRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAutre()
    {
        return $this->createQueryBuilder('pfa')
        ->select('COUNT(pfa.idAutre) as nbProduit')
        ->join('pfa.autre', 'a')
        ->addSelect('pfa', 'a')
        ->where('pfa.vendu = 0')
        ->groupBy('pfa.idAutre')
        ->getQuery()
        ->getResult();       
    }
}
