<?php

namespace IC\AffichageBundle\Repository;

/**
 * TypeLecteurAutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLecteurAutreRepository extends \Doctrine\ORM\EntityRepository
{
}
