<?php

namespace IC\AffichageBundle\Repository;

/**
 * VersionFicheDescriptiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionFicheDescriptiveRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFicheById($id)
    {
        return $this->createQueryBuilder('vfd')
        ->join('vfd.ficheDescriptiveOption', 'fdo')
        ->join('fdo.optionFicheDescriptive', 'ofd')
        ->join('ofd.optionProduitFini', 'opf')
        ->join('fdo.ficheDescriptive', 'fd')
        ->addSelect('vfd', 'fdo', 'ofd', 'opf', 'fd')
        ->where('vfd.id = :id')
        ->setParameter('id', $id)
        ->getQuery()
        ->getResult();
    }
}
