<?php

namespace IC\ProductionBundle\Repository;

/**
 * CarteTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteTestRepository extends \Doctrine\ORM\EntityRepository
{
}
