<?php

namespace IC\ProductionBundle\Repository;

/**
 * ComposantSousTraitantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantSousTraitantRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComposantSt($id)
	{
		return $this->createQueryBuilder('cst')
		->join('cst.sousTraitant', 'st')
		->where('cst.idSousTraitant = :id')
		->setParameter('id', $id)
		->getQuery()
		->getResult();
	}
}
