<?php

namespace IC\ProductionBundle\Repository;

/**
 * HistoriqueProdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueProdRepository extends \Doctrine\ORM\EntityRepository
{
}
