<?php

namespace IC\ProductionBundle\Repository;

/**
 * HistoRepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoRepriseRepository extends \Doctrine\ORM\EntityRepository
{
}
