<?php

namespace IC\ProductionBundle\Repository;

/**
 * LotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastLot()
    {
		return $this->createQueryBuilder('l')
        ->orderby('l.id', 'DESC')
        ->setMaxResults('1')
		->getQuery()
		->getResult();
	}        
}

