<?php

namespace IC\ProductionBundle\Repository;

/**
 * NomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
}
