<?php

namespace IC\ProductionBundle\Repository;

/**
 * ProduitFiniNomenclature
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFiniNomenclature extends \Doctrine\ORM\EntityRepository
{
}
