<?php

namespace IC\ProductionBundle\Repository;

/**
 * ProduitFiniNomenclature
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFiniNomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getComposantNomenclatureProdPF($id)
	{
		return $this->createQueryBuilder('pfn')
		->join('pfn.composant', 'c')
        ->orderBy('c.nom')
		->addSelect('c')
		->where('pfn.idVersion = :id')
		->setParameter('id', $id)
		->getQuery()
		->getResult();
	}
}
