<?php

namespace IC\ProductionBundle\Repository;

/**
 * SousFamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousFamilleRepository extends \Doctrine\ORM\EntityRepository
{
}
