<?php

namespace IC\ProductionBundle\Repository;

/**
 * TypeLecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
